name: second workflow
on: push
jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
            - name: "welcome"
              run: echo "welcome to the code step by step"
    bye-job:
        runs-on: ubuntu-latest
        steps:
            - name: "goodbye"
              run: echo "goodbye to the code step by step"
