name: Validate files
on:
    push:
jobs:
    validate-files:
        runs-on: ubuntu-latest
        steps:
            - name: get-repo-code
              uses: actions/checkout@v4

            - name: Validate html files
              run: test -f index.html && echo "index.html file exists." || (echo "index.html file dos not exist." && exit 1)

            - name: Validate js files
              run: test -f script.js && echo "script.js file exists." || (echo "script.js file dos not exist." && exit 1)

            - name: Validate js code
              run: node --check script.js